# Generated by Django 2.1.7 on 2019-03-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglog',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='reps',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='sets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
