# Generated by Django 2.1.7 on 2019-04-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexerciseset',
            name='unilateral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='unilateral',
            field=models.BooleanField(default=False),
        ),
    ]
