# Generated by Django 2.1.7 on 2019-03-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20190303_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traininglog',
            old_name='sets',
            new_name='set',
        ),
    ]
