# Generated by Django 2.1.7 on 2019-03-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20190303_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglog',
            name='rest_period',
            field=models.IntegerField(blank=True, help_text='In seconds', null=True),
        ),
        migrations.AddField(
            model_name='traininglog',
            name='tempo',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='rest_period',
            field=models.IntegerField(default=90, help_text='In seconds'),
        ),
    ]
